
import { AuthProvider } from "@/hook/AuthProvider"
import { ReduxProvider } from "@/redux/ReduxProvider"
import { Inter } from "next/font/google"
import { Metadata } from "next/types"
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"
import "./global.scss"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Odin ELearning",
    description: "Generated by Odin Team",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ReduxProvider>
                    <AuthProvider/>
                    {children}
                </ReduxProvider>
                <ToastContainer />
            </body>
        </html>
    )
}
